package telas;

import negocios.*;

/*
 * TelaCadastro.java
 *
 * Created on 23 de Novembro de 2002, 16:57
 */

/**
 *
 * @author  leme
 */
public class TelaCadastro extends javax.swing.JDialog {
    
    /** Creates new form TelaCadastro */
    public TelaCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        painelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldFone = new javax.swing.JTextField();
        jTextFieldDataNasc = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Cadastro de novos pacientes");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaCadastro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painelCadastro.setLayout(null);

        painelCadastro.setPreferredSize(new java.awt.Dimension(500, 480));
        painelCadastro.setName("painel");
        jLabel1.setText("Nome");
        painelCadastro.add(jLabel1);
        jLabel1.setBounds(30, 50, 52, 23);

        jLabel2.setText("Data de Nascimento");
        painelCadastro.add(jLabel2);
        jLabel2.setBounds(30, 90, 160, 23);

        jLabel3.setText("Cadastro de Paciente");
        painelCadastro.add(jLabel3);
        jLabel3.setBounds(180, 10, 150, 23);

        painelCadastro.add(jTextFieldNome);
        jTextFieldNome.setBounds(90, 50, 370, 27);

        painelCadastro.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(90, 250, 170, 27);

        jLabel4.setText("Fone");
        painelCadastro.add(jLabel4);
        jLabel4.setBounds(30, 290, 34, 23);

        jLabel5.setText("CEP");
        painelCadastro.add(jLabel5);
        jLabel5.setBounds(30, 250, 25, 23);

        jLabel6.setText("Estado");
        painelCadastro.add(jLabel6);
        jLabel6.setBounds(360, 210, 48, 23);

        jLabel7.setText("Cidade");
        painelCadastro.add(jLabel7);
        jLabel7.setBounds(30, 210, 48, 23);

        jLabel8.setText("Bairro");
        painelCadastro.add(jLabel8);
        jLabel8.setBounds(30, 170, 42, 23);

        jLabel9.setText("Rua");
        painelCadastro.add(jLabel9);
        jLabel9.setBounds(30, 130, 26, 23);

        jLabel10.setText("E-mail");
        painelCadastro.add(jLabel10);
        jLabel10.setBounds(30, 330, 48, 23);

        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });

        painelCadastro.add(jTextFieldRua);
        jTextFieldRua.setBounds(90, 130, 370, 27);

        painelCadastro.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(90, 210, 260, 27);

        painelCadastro.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(90, 170, 370, 27);

        painelCadastro.add(jTextFieldEstado);
        jTextFieldEstado.setBounds(410, 210, 50, 27);

        painelCadastro.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(90, 330, 260, 27);

        painelCadastro.add(jTextFieldFone);
        jTextFieldFone.setBounds(90, 290, 170, 27);

        painelCadastro.add(jTextFieldDataNasc);
        jTextFieldDataNasc.setBounds(190, 90, 100, 27);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        painelCadastro.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(140, 400, 110, 33);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        painelCadastro.add(jButtonCancelar);
        jButtonCancelar.setBounds(265, 400, 110, 33);

        getContentPane().add(painelCadastro, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //Consultorio cons = Consultorio.Instance();
        PacienteComum pac = new PacienteComum ();
        pac.setNome (jTextFieldNome.getText());
        pac.setEndereco (jTextFieldRua.getText(), jTextFieldBairro.getText(), 
                         jTextFieldCidade.getText(), jTextFieldEstado.getText(),
		         jTextFieldCEP.getText(), jTextFieldFone.getText(), 
                         jTextFieldEmail.getText());
        //cons.adicionaPaciente(pac);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaCadastro(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldDataNasc;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
    
}
