/*
 * TelaQuestionario.java
 *
 * Created on 3 de Dezembro de 2002, 09:06
 */

package telas;

import negocios.*;

/**
 *
 * @author  regisb
 */
public class TelaQuestionario extends javax.swing.JDialog {
    Questionario questao = null;
    
    /** Creates new form TelaQuestionario */
    public TelaQuestionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);      
        initComponents();
        questao = Questionario.getPrimeira ();
        if (questao == null) {
            jLabelQuestao.setText("Questionário vazio");            
        } else {
            String texto = "Questão 1 de " + questao.getTotal() + "\n";
            texto += questao.getQuestao();
            jLabelQuestao.setText(texto);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        painel = new javax.swing.JPanel();
        jLabelQuestao = new javax.swing.JLabel();
        jTextFieldResposta = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Question\u00e1rio");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaQuestionario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setLayout(null);

        painel.setPreferredSize(new java.awt.Dimension(400, 300));
        painel.setName("painel");
        jLabelQuestao.setText("Quest\u00e3o");
        painel.add(jLabelQuestao);
        jLabelQuestao.setBounds(20, 40, 330, 80);

        painel.add(jTextFieldResposta);
        jTextFieldResposta.setBounds(20, 150, 330, 27);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        painel.add(jButtonOK);
        jButtonOK.setBounds(100, 230, 100, 33);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        painel.add(jButtonCancelar);
        jButtonCancelar.setBounds(220, 230, 95, 33);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Add your handling code here:
        setVisible (false);
        dispose ();            
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // Add your handling code here:
        // Adicionar questionario a lista do Paciente
        
        // Proxima questao        
        if (questao != null) {
            questao = questao.getProxima();
            String texto = "Questão " + questao.getId() + " de " + questao.getTotal () + "\n";
            texto += questao.getQuestao ();
            jLabelQuestao.setText (texto);
            jTextFieldResposta.setText ("");
        } else {
            // Fecha a janela
            setVisible (false);
            dispose ();            
        }
            
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaQuestionario(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextFieldResposta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelQuestao;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
