/*
 * TelaDespesa.java
 *
 * Created on 27 de Novembro de 2002, 16:15
 */

package telas;

import negocios.*;
import dialogos.*;
import java.util.*;
import java.text.*;

/**
 *
 * @author  leme
 */
public class TelaReceita extends javax.swing.JDialog {
    Consulta consulta;
    
    /** Creates new form TelaDespesa */
    public TelaReceita(java.awt.Frame parent, boolean modal, Consulta novaConsulta) {
        super(parent, modal);
        initComponents();
        rdbNenhum.setVisible(false);
        setLocationRelativeTo(parent);
        consulta = novaConsulta;
        Quantity valor = consulta.calculaCusto();        
        String s = "R$ " + Double.toString (valor.getValor());
        txtValor.setText (s);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        rdgTipoDespesa = new javax.swing.ButtonGroup();
        painel = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        pnlTipoDespesa = new javax.swing.JPanel();
        rdbMensal = new javax.swing.JRadioButton();
        rdbIndividual = new javax.swing.JRadioButton();
        rdbNenhum = new javax.swing.JRadioButton();
        lblPrestacoes = new javax.swing.JLabel();
        txtPrestacoes = new javax.swing.JTextField();

        setTitle("Registro de despesa");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaDespesa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setLayout(null);

        painel.setPreferredSize(new java.awt.Dimension(392, 265));
        painel.setMinimumSize(new java.awt.Dimension(0, 0));
        lblValor.setText("Valor:");
        lblValor.setForeground(new java.awt.Color(0, 0, 153));
        lblValor.setName("lblValor");
        painel.add(lblValor);
        lblValor.setBounds(20, 80, 50, 23);

        txtValor.setName("txtValor");
        txtValor.setEnabled(false);
        painel.add(txtValor);
        txtValor.setBounds(70, 80, 60, 27);

        btnOk.setMnemonic('O');
        btnOk.setText("Ok");
        btnOk.setName("btnOk");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        painel.add(btnOk);
        btnOk.setBounds(40, 200, 90, 33);

        btnLimpa.setMnemonic('L');
        btnLimpa.setText("Limpa");
        btnLimpa.setName("btnLimpa");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        painel.add(btnLimpa);
        btnLimpa.setBounds(150, 200, 90, 33);

        pnlTipoDespesa.setLayout(null);

        pnlTipoDespesa.setBorder(new javax.swing.border.TitledBorder(null, "Tipo da receita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 153)));
        rdbMensal.setText("Mensal");
        rdgTipoDespesa.add(rdbMensal);
        rdbMensal.setName("rdbMensal");
        rdbMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMensalActionPerformed(evt);
            }
        });

        pnlTipoDespesa.add(rdbMensal);
        rdbMensal.setBounds(10, 20, 70, 31);

        rdbIndividual.setText("Individual");
        rdgTipoDespesa.add(rdbIndividual);
        rdbIndividual.setName("rdbIndividual");
        rdbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIndividualActionPerformed(evt);
            }
        });

        pnlTipoDespesa.add(rdbIndividual);
        rdbIndividual.setBounds(90, 20, 100, 31);

        rdgTipoDespesa.add(rdbNenhum);
        rdbNenhum.setName("rdbNenhum");
        rdbNenhum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNenhumActionPerformed(evt);
            }
        });

        pnlTipoDespesa.add(rdbNenhum);
        rdbNenhum.setBounds(180, 0, 20, 31);

        painel.add(pnlTipoDespesa);
        pnlTipoDespesa.setBounds(10, 0, 200, 60);

        lblPrestacoes.setText("N\u00famero de presta\u00e7\u00f5es:");
        lblPrestacoes.setForeground(new java.awt.Color(0, 0, 153));
        lblPrestacoes.setName("lblPrestacoes");
        painel.add(lblPrestacoes);
        lblPrestacoes.setBounds(20, 130, 170, 23);

        txtPrestacoes.setName("txtPrestacoes");
        txtPrestacoes.setEnabled(false);
        painel.add(txtPrestacoes);
        txtPrestacoes.setBounds(190, 130, 30, 27);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void rdbNenhumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNenhumActionPerformed
        txtPrestacoes.setText(null);
        txtPrestacoes.disable();
    }//GEN-LAST:event_rdbNenhumActionPerformed

    private void rdbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIndividualActionPerformed
        txtPrestacoes.setText(null);
        txtPrestacoes.disable();
    }//GEN-LAST:event_rdbIndividualActionPerformed

    private void rdbMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMensalActionPerformed
        txtPrestacoes.enable();
    }//GEN-LAST:event_rdbMensalActionPerformed

    private void limpaCampos()
    {
        rdbNenhum.setSelected(true);
        txtValor.setText(null);
        txtPrestacoes.setText(null);
    }

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Quantity valor = new Quantity(0,Unit.get(Unit.REAL));
        int prestacoes = 0;
        PoliticaDeReceita politica = null;
        boolean dadosValidos = true;
    
        valor = consulta.calculaCusto();        
        String s = "R$ " + Double.toString (valor.getValor());
        txtValor.setText (s);
        if (rdbMensal.isSelected())
        {
            try {
                prestacoes = Integer.parseInt(txtPrestacoes.getText());
                politica = new ReceitaMensal(prestacoes);
            }
            catch (NumberFormatException nfe) {
                new DialogoConfirmacao(new javax.swing.JFrame(), true , "Erro: prestações inv\u00e1lidas",
                                       "Formato de valor inteiro inv\u00e1lido.").show();

                dadosValidos = false;
            }
        }
        else
            if (rdbIndividual.isSelected())
                politica = new ReceitaIndividual();
            else {
                new DialogoConfirmacao(new javax.swing.JFrame(), true , "Erro: selecione o tipo de receita",
                                       "Tipo da receita em branco.").show();
                dadosValidos = false;
            }
        
        if (dadosValidos) {
            Receita receita = new Receita(consulta.getData().getInicio(), consulta.getDescricao(), valor, politica);
            consulta.adicionaReceita (receita);
            Consultorio consultorio = Consultorio.Instance();
            consultorio.adicionaReceita(receita);
             new DialogoConfirmacao(new javax.swing.JFrame(), true, "Aviso",
                                    "Receita inclu\u00edda com sucesso.").show();
            limpaCampos();
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        limpaCampos();        
    }//GEN-LAST:event_btnLimpaActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaDespesa(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton rdbNenhum;
    private javax.swing.JRadioButton rdbMensal;
    private javax.swing.JPanel pnlTipoDespesa;
    private javax.swing.JLabel lblPrestacoes;
    private javax.swing.JButton btnOk;
    private javax.swing.JRadioButton rdbIndividual;
    private javax.swing.ButtonGroup rdgTipoDespesa;
    private javax.swing.JTextField txtPrestacoes;
    private javax.swing.JTextField txtValor;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
