/*
 * TelaPrincipal.java
 *
 * Created on 23 de Novembro de 2002, 15:11
 */

package telas;

import negocios.*;

/**
 *
 * @author  leme
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        Consultorio.Instance().efetuaBalanco(false);
        setSize(1029,764);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        desktop = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuPacientes = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenuItem();
        menuConsultaV = new javax.swing.JMenuItem();
        menuContabilidade = new javax.swing.JMenu();
        menuCobranca = new javax.swing.JMenuItem();
        menuDespesa = new javax.swing.JMenuItem();
        menuBalanco = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuGeraBalanco = new javax.swing.JMenuItem();

        setTitle("Sistema Informatizado de Consult\u00f3rio Odontol\u00f3gico");
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setName("telaPrincipal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        menuPrincipal.setName("menuPrincipal");
        menuPacientes.setMnemonic('P');
        menuPacientes.setLabel("Pacientes");
        menuPacientes.setName("menuPacientes");
        menuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacientesActionPerformed(evt);
            }
        });

        menuCadastro.setMnemonic('C');
        menuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastro.setText("Cadastro de novos pacientes");
        menuCadastro.setName("menuCadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerfored(evt);
            }
        });

        menuPacientes.add(menuCadastro);

        menuConsulta.setMnemonic('A');
        menuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuConsulta.setText("Agendamento de consulta");
        menuConsulta.setName("menuConsulta");
        menuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaActionPerformed(evt);
            }
        });

        menuPacientes.add(menuConsulta);

        menuRelatorio.setMnemonic('R');
        menuRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatorio.setText("Relat\u00f3rio de tratamento");
        menuRelatorio.setName("menuRelatorio");
        menuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioActionPerformed(evt);
            }
        });

        menuPacientes.add(menuRelatorio);

        menuConsultaV.setMnemonic('P');
        menuConsultaV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuConsultaV.setText("Consultas Marcadas");
        menuConsultaV.setName("menuExame");
        menuConsultaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaVActionPerformed(evt);
            }
        });

        menuPacientes.add(menuConsultaV);

        menuPrincipal.add(menuPacientes);

        menuContabilidade.setMnemonic('C');
        menuContabilidade.setLabel("Contabilidade");
        menuContabilidade.setName("menuContabilidade");
        menuCobranca.setMnemonic('P');
        menuCobranca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuCobranca.setText("Previs\u00e3o de pagamento");
        menuCobranca.setName("menuCobranca");
        menuCobranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCobrancaActionPerformed(evt);
            }
        });

        menuContabilidade.add(menuCobranca);

        menuDespesa.setMnemonic('R');
        menuDespesa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuDespesa.setText("Registro de despesa");
        menuDespesa.setName("menuDespesa");
        menuDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDespesaActionPerformed(evt);
            }
        });

        menuContabilidade.add(menuDespesa);

        menuBalanco.setMnemonic('B');
        menuBalanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuBalanco.setText("Balan\u00e7o mensal");
        menuBalanco.setName("menuBalanco");
        menuBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalancoActionPerformed(evt);
            }
        });

        menuContabilidade.add(menuBalanco);

        menuContabilidade.add(jSeparator1);

        menuGeraBalanco.setText("Gera balan\u00e7o");
        menuGeraBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeraBalancoActionPerformed(evt);
            }
        });

        menuContabilidade.add(menuGeraBalanco);

        menuPrincipal.add(menuContabilidade);

        setJMenuBar(menuPrincipal);

        pack();
    }//GEN-END:initComponents

    private void menuGeraBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeraBalancoActionPerformed
        Consultorio.Instance().efetuaBalanco(true);
    }//GEN-LAST:event_menuGeraBalancoActionPerformed

    private void menuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacientesActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_menuPacientesActionPerformed

    private void menuBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalancoActionPerformed
        new TelaBalanco(this,true).show();
    }//GEN-LAST:event_menuBalancoActionPerformed

    private void menuDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDespesaActionPerformed
        new TelaDespesa(this,true).show();
    }//GEN-LAST:event_menuDespesaActionPerformed

    private void menuCobrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCobrancaActionPerformed
        new TelaCobranca(this,true).show();
    }//GEN-LAST:event_menuCobrancaActionPerformed

    private void menuConsultaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaVActionPerformed
        new TelaConsultaV(this,true).show();
    }//GEN-LAST:event_menuConsultaVActionPerformed

    private void menuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioActionPerformed
        new TelaRelatorio(this,true).show();
    }//GEN-LAST:event_menuRelatorioActionPerformed

    private void menuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaActionPerformed
        new TelaConsulta(this,true).show();
    }//GEN-LAST:event_menuConsultaActionPerformed

    private void menuCadastroActionPerfored(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerfored
        new TelaCadastro(this,true).show();
    }//GEN-LAST:event_menuCadastroActionPerfored
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaPrincipal().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuContabilidade;
    private javax.swing.JMenu menuPacientes;
    private javax.swing.JMenuItem menuRelatorio;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuCadastro;
    private javax.swing.JMenuItem menuGeraBalanco;
    private javax.swing.JMenuItem menuDespesa;
    private javax.swing.JMenuItem menuBalanco;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem menuConsultaV;
    private javax.swing.JMenuItem menuConsulta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuCobranca;
    // End of variables declaration//GEN-END:variables
    
}
