/*
 * TelaCobranca.java
 *
 * Created on 27 de Novembro de 2002, 16:24
 */

package telas;

import negocios.*;
import dialogos.*;
import java.util.*;
import java.text.*;

/**
 *
 * @author  leme
 */
public class TelaCobranca extends javax.swing.JDialog {
    
    /** Creates new form TelaCobranca */
    public TelaCobranca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        painel = new javax.swing.JPanel();
        lblPeriodo = new javax.swing.JLabel();
        lblDataInic = new javax.swing.JLabel();
        lblDataFim = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtDataInic = new javax.swing.JTextField();
        txtDataFim = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setTitle("Previs\u00e3o de pagamento");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaCobranca");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setLayout(null);

        painel.setPreferredSize(new java.awt.Dimension(300, 237));
        lblPeriodo.setText("Per\u00edodo de abrang\u00eancia:");
        lblPeriodo.setForeground(new java.awt.Color(0, 7, 153));
        lblPeriodo.setName("lblPeriodo");
        painel.add(lblPeriodo);
        lblPeriodo.setBounds(10, 10, 180, 23);

        lblDataInic.setText("Data inicial:");
        lblDataInic.setForeground(new java.awt.Color(0, 0, 153));
        lblDataInic.setName("lblDataInic");
        painel.add(lblDataInic);
        lblDataInic.setBounds(30, 40, 90, 23);

        lblDataFim.setText("Data final:");
        lblDataFim.setForeground(new java.awt.Color(0, 0, 153));
        lblDataFim.setName("lblDataFim");
        painel.add(lblDataFim);
        lblDataFim.setBounds(30, 70, 80, 23);

        lblValor.setText("Valor:");
        lblValor.setForeground(new java.awt.Color(0, 0, 153));
        lblValor.setName("lblValor");
        lblValor.setEnabled(false);
        painel.add(lblValor);
        lblValor.setBounds(90, 200, 50, 23);

        txtDataInic.setName("txtDataInic");
        painel.add(txtDataInic);
        txtDataInic.setBounds(120, 40, 90, 27);

        txtDataFim.setName("txtDataFim");
        painel.add(txtDataFim);
        txtDataFim.setBounds(110, 70, 90, 27);

        txtValor.setName("txtValor");
        txtValor.setEnabled(false);
        painel.add(txtValor);
        txtValor.setBounds(140, 200, 60, 27);

        btnOk.setMnemonic('O');
        btnOk.setText("Ok");
        btnOk.setName("btnOk");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        painel.add(btnOk);
        btnOk.setBounds(50, 120, 90, 33);

        btnLimpa.setMnemonic('L');
        btnLimpa.setText("Limpa");
        btnLimpa.setName("btnLimpa");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        painel.add(btnLimpa);
        btnLimpa.setBounds(160, 120, 90, 33);

        lblResultado.setText("Resultado dos pagamentos:");
        lblResultado.setForeground(new java.awt.Color(0, 0, 153));
        lblResultado.setName("lblResultado");
        painel.add(lblResultado);
        lblResultado.setBounds(50, 170, 200, 23);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        boolean dadosValidos = true;
        
        Date dataInic = sdf.parse(txtDataInic.getText(),new ParsePosition(0));
        if (dataInic == null)
        {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Erro: data inicial inv\u00e1lida",
                                   "Formato de data inv\u00e1lido.").show();
            dadosValidos = false;
        }

        Date dataFim = sdf.parse(txtDataFim.getText(),new ParsePosition(0));
        if (dataFim == null)
        {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Erro: data final inv\u00e1lida",
                                   "Formato de data inv\u00e1lido.").show();
            dadosValidos = false;
        }
        
        if (dadosValidos) {
            Consultorio consultorio = Consultorio.Instance();
            DateRange faixaData = new DateRange(dataInic,dataFim);
            txtValor.setText(Double.toString(consultorio.calculaPagamento(faixaData).getValor()));
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        txtDataInic.setText(null);
        txtDataFim.setText(null);
        txtValor.setText(null);
    }//GEN-LAST:event_btnLimpaActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaCobranca(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JLabel lblDataInic;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField txtDataInic;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JTextField txtValor;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
